### ISSUE TITLE
No module named voidpp_tools.json_config

### ISSUE THREAD

**Issue by ghost** [voidpp/PCA9685-driver-http#1]
Hi,

I reinstalled my Raspi an now there is the following error.
Did I miss anything?
```
Traceback (most recent call last):
  File "run-dev-server.py", line 2, in <module>
    from pca9685_driver_http.app import app
  File "/home/pi/bin/PCA9685-driver-http/pca9685_driver_http/app.py", line 6, in <module>
    from .config import config, config_loader
  File "/home/pi/bin/PCA9685-driver-http/pca9685_driver_http/config.py", line 2, in <module>
    from voidpp_tools.json_config import JSONConfigLoader
ImportError: No module named voidpp_tools.json_config
```

Thank You

**Comment by ghost** [comment]
Running Setup fixed it.
