### ISSUE TITLE
IOError: 121

### ISSUE THREAD

**Issue by ghost** [voidpp/PCA9685-driver-http#2]
The program crashes with the IOError 121.
I cannot think of anything I changed.
Do you know anything?

```
2017-09-02 14:52:44,015 - INFO - pca9685_driver_http.app - app.py:16: Config loaded from /home/pi/bin/PCA9685-driver-http/pca9685-driver-http-config.json
Traceback (most recent call last):
  File "run-dev-server.py", line 2, in <module>
    from pca9685_driver_http.app import app
  File "/home/pi/bin/PCA9685-driver-http/pca9685_driver_http/app.py", line 22, in <module>
    devices[name].wake()
  File "/usr/local/lib/python2.7/dist-packages/pca9685_driver/device.py", line 153, in wake
    self.write(Registers.MODE_1, self.mode_1 & (255 - (1 << Mode1.SLEEP)))
  File "/usr/local/lib/python2.7/dist-packages/pca9685_driver/device.py", line 80, in mode_1
    return self.read(Registers.MODE_1)
  File "/usr/local/lib/python2.7/dist-packages/pca9685_driver/device.py", line 171, in read
    return self.__bus.read_byte_data(self.__address, reg)
  File "/usr/local/lib/python2.7/dist-packages/smbus/util.py", line 59, in validator
    return fn(*args, **kwdefaults)
  File "/usr/local/lib/python2.7/dist-packages/smbus/smbus.py", line 132, in read_byte_data
    raise IOError(ffi.errno)
IOError: 121
```

**Comment by voidpp** [comment]
Well, I've never encountered this error, but I think if you didn't change anything maybe it's a hw or os issue.
